version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "Abcd=1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  api:
    image: donorflow-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=db;Database=DonorFlowDb;User Id=sa;Password=Abcd=1234;
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  sql-data: